## Numpy Assignment

Q) Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import math
import numpy as np
def create_output_matrix(vector,n,increasing=False):
    l=[]
    k=[]
    if not increasing:
        
        for j in range(n-1,-1,-1):
            m=[int(math.pow(i,j)) for i in vector]
            l.append(m)
        
        for i in range(len(vector)):
            m=[l[j][i] for j in range(n)]
            k.append(m)
            
        mat=np.array(k).reshape(len(vector),n)
        print("When incresing = False, the matrix is\n",mat)
        
    elif increasing:
        
        for j in range(n):
            m=[int(math.pow(i,j)) for i in vector]
            l.append(m)
          
        for i in range(len(vector)):
            m=[l[j][i] for j in range(n)]
            k.append(m) 
            
        mat=np.array(k).reshape(len(vector),n)
        print("When incresing = True, the matrix is\n",mat)

inputs=input('Enter input vector in comma seperated : ')
inputs=inputs.split(',')
put=[int(item) for item in inputs]
no_columns=int(input("How many columns required : "))
create_output_matrix(put,no_columns,False)
create_output_matrix(put,no_columns,True)



Enter input vector in comma seperated : 1,2,4,6,8,10
How many columns required : 5
When incresing = False, the matrix is
 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]]
When incresing = True, the matrix is
 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]]


## -------------------------------------------------------------------------------------------------

In [2]:
data=[3,5,7,2,8,10,11,65,72,81,99,100,150]
window=3
l=[]
for i in range(len(data)-(window-1)):
    m=0.0
    for j in range(window):
        m+=data[i+j]
    l.append(m/window)
print(l)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
